### ISSUE TITLE
Running a Palm application - unclear how to install multiple files

### ISSUE THREAD

**Issue by voltagex** [libretro/Mu#13]
Hi,
I've grabbed http://web.archive.org/web/20070312052007if_/http://www.trvlink.com:80/download/oneworld/onepalm.zip, which should be a travel itinerary app. In that zip are 

```
oneworld.pdb
oneworld.prc
innoflights.prc
mathlib.prc
```

Running oneworld.prc brings up an icon, but it seems to crash.

I am assuming the application needs all of the data files, but how can I provide them to the core?

**Comment by XerTheSquirrel** [comment]
Hi!

Looks like PDB is not in the list of valid content, so I added it here in <https://github.com/libretro/libretro-super/pull/1585>. Whenever the next _libretro-super_ core info gets loaded in, you should be able to update your core information and the core itself.

Currently you can only install a single file at a time, so you would have to select each PRC and PDB you want to install and load the core with that. Once all of them are loaded in, it should work. Loading content places the PRC/PDB into the device's RAM storage.

For the future I plan to support loading ZIP files containing everything to be installed in one go.

**Comment by trebrick** [comment]
are prc/pdbs supposed to stay installed when loading/installing a new one? every time i load a new one the core seems to reset and there are no previous installs showing. so the OPs issue would still happen.

**Comment by XerTheSquirrel** [comment]
They should stay when installed to RAM, however if the core is set to autosave/autoload state on enter/exit in RetroArch then it is likely whatever was installed would be deleted.

**Comment by trebrick** [comment]
Thanks for the reply. I dont have autosave autoload on though. Maybe im loading the core and content wrong? Is there a certain way it has to be done? Loading any content ignores the ram file it seems and when i close and reload and open the core its back using it again and the content i just loaded is gone.

**Comment by XerTheSquirrel** [comment]
Do you have per content save states enabled, where there are specific save states for each specific game kept separated?

**Comment by gingerbeardman** [comment]
I am also unable to load multiple files using RetroArch, the emulator resets with each content load. An additional RAM file is created for each PRC/PDB I try to "add"

**Comment by XerTheSquirrel** [comment]
As of v1.3.1, you can package those into a ZIP file and then load the ZIP file on RetroArch.
