### ISSUE TITLE
Palm files not associated with Mu core

### ISSUE THREAD

**Issue by gab** [libretro/Mu#23]
Running on Retroarch 1.10.3 with Mu 1.3.0 https://github.com/libretro/Mu/commit/1361da04014d77b8bec13e050a71bf7bf8ce5543.
palmos41-en-m515.rom checksum is 83CB1D1C76E568B916DC2E7C0BF669F6

Retroarch doesn't recognize _any_ of the .prc, .pdb, etc file types as belonging to the Mu core. The only way I managed to make it load a file was through a manual filter, picking the folder, core and file extensions myself.

(There's also no way to load multiple files btw, loading a file restarts the emulator - that's on a fresh Retroarch install and I haven't found any option to change this behavior. The only workaround seems to be creating a RAM file in advance through the RamBuilder (which is essentially the Qt version IIUC), but that's pretty obscure and only available in the parent repo.)

**Comment by gingerbeardman** [comment]
Indeed, you have to use RAM Builder

**Comment by gab** [comment]
> Indeed, you have to use RAM Builder

You don't have to. As stated above, if you're only launching a single .prc file, manually associating with the core works.

So it's worth associating the core with those file types properly.

**Comment by gingerbeardman** [comment]
Sorry, I was referring only to your point about multiple files

**Comment by XerTheSquirrel** [comment]
I figured out the issue for this and will be putting in a fix, as for multiple files I might just implement ZIP support real quickly and see if I can get that done. I am just keeping this issue to the file associations.

**Comment by XerTheSquirrel** [comment]
I added all the files into the supported entries, and also added ZIP for future work.

**Comment by gab** [comment]
Thanks!
