### ISSUE TITLE
No Mu core on Apple macOS arm64

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/Mu#24]
There is no Mu core on Mac arm64.

Let me know how I can assist with checking this compiled and/or adding this in some way.

**Comment by XerTheSquirrel** [comment]
I can get that added tomorrow if I remember to do so, but it would be simple to add.

**Comment by XerTheSquirrel** [comment]
I added it, so that build is here at <https://git.libretro.com/libretro/Mu/-/jobs/2570206>, it will eventually pop up in the core updater. If there are issues with ARM please do make other issues.

**Comment by gingerbeardman** [comment]
Thanks very much!
