### ISSUE TITLE
Builds fail for osx-arm64 in the libretro buildbot

### ISSUE THREAD

**Issue by zoltanvb** [libretro/Mu#27]
Builds for osx-arm64 are failing on libretro buildbot, with:
`Non-fat file: mu_libretro.dylib is architecture: x86_64`
Logs time out quickly, so go to Libretro discord and check the gitlab-ci channel for latest pipeline results.

Probably all it needs is the "CROSS-COMPILE" section, which was pointed out by warmenhoven and solved same problem in  ep128emu: https://github.com/libretro/ep128emu-core/commit/ee982f6fb14c0e1ec4415ffdf75b9d27fe1bff3f (MINVERSION is likely not relevant here).

**Comment by XerTheSquirrel** [comment]
Will take a look and get it fixed up! There must have been something that changed since the ARM build has worked previously.
